# Generated by Django 5.2.1 on 2025-05-30 15:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='dateAJout',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 5, 30))]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.IntegerField(default=656569962, unique=True),
            preserve_default=False,
        ),
    ]
