# Generated by Django 5.2.1 on 2025-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_utilisateur_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
