# Generated by Django 5.2.1 on 2025-07-23 15:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='utilisateur_ptr',
        ),
        migrations.AlterField(
            model_name='produit',
            name='dateAJout',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 7, 23))]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
