# Generated by Django 5.2.1 on 2025-07-23 15:48

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(default='Bafoussam', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+237656789878', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
