# Generated by Django 5.2.1 on 2025-08-25 15:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dateAJout',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 8, 25))]),
        ),
    ]
