# Generated by Django 5.2.1 on 2025-08-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_panier_client_alter_produit_dateajout'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='dateSoumission',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
