# Generated by Django 5.2.1 on 2025-08-30 09:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_panier_datesoumission'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='ancienPrix',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='dateAJout',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 8, 30))]),
        ),
    ]
